FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir torch torchvision pillow

COPY mobilenet_v2.pt .
COPY inference.py .

ENTRYPOINT ["python", "inference.py"]