{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aiops-quality-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aiops-quality-service.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aiops-quality-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: 15s
{{- end }}
