apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-from-manifests
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: "https://github.com/your-org/mlops.git"
    path: mlops-experiments/manifests/postgres
    targetRevision: lesson-8-9
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
