apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
  namespace: infra-tools
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-pushgateway
    targetRevision: "2.0.0"
    helm:
      releaseName: pushgateway
      valuesObject:
        service:
          type: ClusterIP
          port: 9091
        fullnameOverride: "pushgateway"
        serviceMonitor:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
